### ISSUE TITLE
How do I start it?

### ISSUE THREAD

**Issue by jackmatt2** [egomezal/irpgeditor#4]
I downloaded master, unzipped it.

How do I start the application?  There is nothing in README on this.

**Comment by jackmatt2** [comment]
I got it working by importing the project into eclipse and exporting it as an executable jar file.  Would be nice to have some instructions in the README on how to do this especially for people unfamiliar with Java.

**Comment by jackmatt2** [comment]
Possibly a dist folder which has bundled jar files might be a better option.

**Comment by egomezal** [comment]
You use https://github.com/egomezal/irpgeditor/releases for binaries
